<?php

	class SiteTreeExtension extends DataObjectDecorator {
	
		/* Append parent's static variables. */
		function extraStatics() {
		
			return array(
				/* Database fields. */
				'db' => array(
					'MetaKeywordsAppend' => 'Boolean',
					'MetaDescriptionAppend' => 'Enum("Beginning, End, No")',
					'ExtraMetaAppend' => 'Boolean'
				),
				/* Default database field values. */
				'defaults' => array(
					'MetaKeywordsAppend' => true,
					'MetaDescriptionAppend' => 'Beginning',
					'ExtraMetaAppend' => true
				)
			);
		}
	
		/**
		 * Return the title, description, keywords and language metatags.
		 * 
		 * @param string $tags Reference to the tags generated by the parent class
		 */
		public function MetaTags(&$tags) {
			
			/* HACK ALERT: Was $includeTitle set in the calling function? */
			strpos($tags, '<title>') ? $includeTitle = true : $includeTitle = false;
			
			$site_config = SiteConfig::current_site_config();
			
			$tags = "";
			
			if($includeTitle) {
				$tags .= "<title>" . Convert::raw2xml(($this->MetaTitle) ? $this->MetaTitle : $this->Title) . "</title>\n";
			}

			$tags .= "<meta name=\"generator\" content=\"SilverStripe - http://silverstripe.org\" />\n";

			$charset = ContentNegotiator::get_encoding();
			$tags .= "<meta http-equiv=\"Content-type\" content=\"text/html; charset=$charset\" />\n";
			if($this->owner->MetaKeywords || ($site_config->MetaKeywords and $this->owner->MetaKeywordsAppend)) {
				$keywords = array();
				if($site_config->MetaKeywords and $this->owner->MetaKeywordsAppend) $keywords[] = $site_config->MetaKeywords;
				if($this->owner->MetaKeywords) $keywords[] = $this->owner->MetaKeywords;
				$tags .= "<meta name=\"keywords\" content=\"" . Convert::raw2att(implode(', ', $keywords)) . "\" />\n";
			}
			if($this->owner->MetaDescription || ($site_config->MetaDescription and $this->owner->MetaDescriptionAppend != 'No')) {
				$description = array();
				if($site_config->MetaDescription and $this->owner->MetaDescriptionAppend == 'Beginning') $description[] = $site_config->MetaDescription;
				if($this->owner->MetaDescription) $description[] = $this->owner->MetaDescription;
				if($site_config->MetaDescription and $this->owner->MetaDescriptionAppend == 'End') $description[] = $site_config->MetaDescription;
				$tags .= "<meta name=\"description\" content=\"" . Convert::raw2att(implode(' ', $description)) . "\" />\n";
			}
			if($this->owner->ExtraMeta || ($site_config->ExtraMeta and $this->owner->ExtraMetaAppend)) { 
				if($this->owner->ExtraMeta) $tags .= $this->owner->ExtraMeta . "\n";
				if($site_config->ExtraMeta and $this->owner->ExtraMetaAppend) $tags .= $site_config->ExtraMeta . "\n";
			}
			
			/* Here we add the code required for analytics for each vendor. */
			
			/* Google Analytics. */
			if($site_config->AnalyticsGoogleEnabled and $site_config->AnalyticsGoogleAccountNumber) {
				$tags .= "
				<script type=\"text/javascript\">
				var _gaq = _gaq || [];
				_gaq.push(['_setAccount', '{$site_config->AnalyticsGoogleAccountNumber}']);
				_gaq.push(['_trackPageview']);
				(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })();
				</script>
				";
			}
			
			/* Yahoo! Web Analytics. */
			if($site_config->AnalyticsYahooEnabled and $site_config->AnalyticsYahooTrackingId) {
			
				/* Parse YWA Variables to JavaScript. */
				$ywa_variables = "";
				foreach($site_config->YahooAnalyticsVariables() as $variable) {
					$ywa_variables .= "
					YWATracker.set{$variable->Name}(\"{$variable->Value}\");\n
					";
				}
			
				$tags .= "
				<script type=\"text/javascript\" src=\"http://d.yimg.com/mi/ywa.js\"></script>
				<script type=\"text/javascript\">
				YWATracker = YWA.getTracker(\"{$site_config->AnalyticsYahooTrackingId}\");
				{$ywa_variables}
				YWATracker.submit();
				</script>
				";
			}
			
		}
		
		/* New/modified fields for the CMS. */
		public function updateCMSFields($fields) {
			
			$fields->addFieldToTab('Root.Content.Metadata', new CheckboxField('MetaKeywordsAppend', 'Append global keywords?'), 'MetaDescription');
			$fields->addFieldToTab('Root.Content.Metadata', new DropdownField('MetaDescriptionAppend', 'Append global description?',  array('Beginning' => 'Yes, to the beginning', 'End' => 'Yes, to the end', 'No' => 'No')), 'ExtraMeta');
			$fields->addFieldToTab('Root.Content.Metadata', new CheckboxField('ExtraMetaAppend', 'Append global custom meta tags?'));
			
			return $fields;
		}
		
	}

?>