<?php

	class SiteTreeExtension extends DataObjectDecorator {
	
		function extraStatics() {
		
			return array(
				'db' => array(
					'MetaKeywordsAppend' => 'Boolean',
					'MetaDescriptionAppend' => 'Enum("Beginning, End, No")'
				),
				'defaults' => array(
					'MetaKeywordsAppend' => 1,
					'MetaDescriptionAppend' => 'Beginning'
				)
			);
		}
	
		/**
		 * Return the title, description, keywords and language metatags.
		 * 
		 * @param string $tags Reference to the tags generated by the parent class
		 */
		public function MetaTags(&$tags) {
			
			/* HACK ALERT: Was $includeTitle set in the calling function? */
			strpos($tags, '<title>') ? $includeTitle = true : $includeTitle = false;
			
			$site_config = SiteConfig::current_site_config();
			
			$tags = "";
			
			if($includeTitle) {
				$tags .= "<title>" . Convert::raw2xml(($this->MetaTitle) ? $this->MetaTitle : $this->Title) . "</title>\n";
			}

			$tags .= "<meta name=\"generator\" content=\"SilverStripe - http://silverstripe.org\" />\n";

			$charset = ContentNegotiator::get_encoding();
			$tags .= "<meta http-equiv=\"Content-type\" content=\"text/html; charset=$charset\" />\n";
			if($this->owner->MetaKeywords || ($site_config->MetaKeywords and $this->owner->MetaKeywordsAppend)) {
				$keywords = array();
				if($site_config->MetaKeywords and $this->owner->MetaKeywordsAppend) $keywords[] = $site_config->MetaKeywords;
				if($this->owner->MetaKeywords) $keywords[] = $this->owner->MetaKeywords;
				$tags .= "<meta name=\"keywords\" content=\"" . Convert::raw2att(implode(', ', $keywords)) . "\" />\n";
			}
			if($this->owner->MetaDescription || ($site_config->MetaDescription and $this->owner->MetaDescriptionAppend != 'No')) {
				$description = array();
				if($site_config->MetaDescription and $this->owner->MetaDescriptionAppend == 'Beginning') $description[] = $site_config->MetaDescription;
				if($this->owner->MetaDescription) $description[] = $this->owner->MetaDescription;
				if($site_config->MetaDescription and $this->owner->MetaDescriptionAppend == 'End') $description[] = $site_config->MetaDescription;
				$tags .= "<meta name=\"description\" content=\"" . Convert::raw2att(implode(' ', $description)) . "\" />\n";
			}
			if($this->owner->ExtraMeta || $site_config->ExtraMeta) { 
				if($this->owner->ExtraMeta) $tags .= $this->owner->ExtraMeta . "\n";
				if($site_config->ExtraMeta) $tags .= $site_config->ExtraMeta . "\n";
			}

		}
		
		public function updateCMSFields($fields) {
		
			$fields->addFieldToTab('Root.Content.Metadata', new CheckboxField('MetaKeywordsAppend', 'Append global keywords?'), 'MetaDescription');
			$fields->addFieldToTab('Root.Content.Metadata', new DropdownField('MetaDescriptionAppend', 'Append global description?',  array('Beginning' => 'Yes, to the beginning', 'End' => 'Yes, to the end', 'No' => 'No')), 'ExtraMeta');
			
			return $fields;
		}
		
	}

?>